'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3603
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")>  _
Partial Friend NotInheritable Class DefinitionQueryLayers
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As DefinitionQueryLayers = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New DefinitionQueryLayers),DefinitionQueryLayers)
    
    Public Shared ReadOnly Property [Default]() As DefinitionQueryLayers
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property Setting() As String
        Get
            Return CType(Me("Setting"),String)
        End Get
        Set
            Me("Setting") = value
        End Set
    End Property
End Class
